maratona_intercon2016/core/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

maratona_intercon2016/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('maratona_intercon2016.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

maratona_intercon2016/core/models.py
from django.db import models


class Eleitor(models.Model):
    uf = models.CharField(blank=True, null=True, max_length=2)
    municipio = models.CharField(max_length=50, blank=True, null=True)
    cod_municipio_tse = models.IntegerField()
    zona = models.ForeignKey(
        'Bairro', verbose_name='zona_eleitor', null=True, blank=True)
    sexo = models.CharField(max_length=50, blank=True, null=True)
    faixa_etaria = models.CharField(max_length=50, blank=True, null=True)
    grau_de_escolaridade = models.CharField(
        max_length=50, blank=True, null=True)
    qtd_eleitores_no_perfil = models.IntegerField()

    class Meta:
        ordering = ('id',)
        verbose_name = 'eleitor'
        verbose_name_plural = 'eleitores'

    def __str__(self):
        return str(self.id)


class Voto(models.Model):
    zona = models.ForeignKey(
        'Bairro', verbose_name='zona_voto', null=True, blank=True)
    nome_candidato = models.CharField(max_length=50)
    total_votos = models.IntegerField()


class Bairro(models.Model):
    zona = models.IntegerField(unique=True)
    bairro = models.CharField(
        unique=True, max_length=50, blank=True, null=True,)

    def __str__(self):
        return self.bairro

    class Meta:
        ordering = ('bairro',)

maratona_intercon2016/core/views.py
from django.shortcuts import render
from .models import Bairro, Voto, Eleitor


def index(request):
    votos = ''
    eleitores = ''
    bairros = Bairro.objects.all()
    q = request.GET.get('bairro')
    if q:
        votos = Voto.objects.filter(zona__bairro=q).order_by('-total_votos')
        eleitores = Eleitor.objects.filter(zona__bairro=q).order_by('-qtd_eleitores_no_perfil')
    context = {'bairros': bairros, 'votos': votos, 'eleitores': eleitores}
    return render(request, 'index.html', context)

maratona_intercon2016/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Marathona Hacker Intercon 2016 - {% block title  %}{% endblock %}</title>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/raphael-min.js' %}"></script>
    <script src="{% static 'js/morris.min.js' %}"></script>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Morris CSS -->
    <link href="{% static 'css/morris.css' %}" rel="stylesheet">
    <!-- Main CSS -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>

  <body class="index">
    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">

            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">GruPy-SP Maratona Hacker - Intercon 2016</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">Sobre</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact">Contato</a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>

    <!-- Header -->
    <div id="mainHeader" class="jumbotron">
        <div class="container">
          {% block header %}{% endblock%}
        </div>
    </div>

    <div class="container">
       {% block content %}{% endblock %}
    </div>

  </body>
</html>

maratona_intercon2016/core/templates/index.html
{% extends 'base.html' %}

{% block header %}
    <div class="page-header text-center">
        <h1>GruPy-SP</h1>
        <h2>Maratona Hacker - Intercon 2016</h2>
    </div>
{% endblock %}

{% block content %}

    <form class="form-inline" action="." method="GET">

        <div class="form-group">
            <label for="id_bairro">Bairro</label>
            {% if bairros %}
                <select name="bairro" id="id_bairro">
                    {% for bairro in bairros %}
                        <option value="{{ bairro.bairro }}">{{ bairro.bairro }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <select name="bairros" id="id_bairros">
                    <option value="">---</option>
                </select>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-default">
            Buscar
        </button>

        <br />
    </form>

    <div id="candidatos_bairro">
        <table class="table">
            <thead>
                <tr>
                    <th>Candidato</th>
                    <th>Total de Votos</th>
                </tr>
            </thead>
            <tbody>
                {% if votos %}
                    {% for voto in votos %}
                        <tr>
                            <td>{{ voto.nome_candidato }}</td>
                            <td>{{ voto.total_votos }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>

    <div id="eleitores_bairro">
        <table class="table">
            <thead>
                <tr>
                    <th>Sexo</th>
                    <th>Faixa Etária</th>
                    <th>Escolaridade</th>
                    <th>Quantidade de Eleitores</th>
                </tr>
            </thead>
            <tbody>
                {% if eleitores %}
                    {% for eleitor in eleitores %}
                        <tr>
                            <td>{{ eleitor.sexo }}</td>
                            <td>{{ eleitor.faixa_etaria }}</td>
                            <td>{{ eleitor.grau_de_escolaridade }}</td>
                            <td>{{ eleitor.qtd_eleitores_no_perfil }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}